export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";
export const FILTERED_POKEMONS = "FILTERED_POKEMONS";
export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
